### ISSUE TITLE
OWM Api Key Error

### ISSUE THREAD

**Issue by xkzkx** [jefflaplante/forecast#4]
Hiya,

I followed the guide, created the .env file in the main directory, but still getting this error:

`
pi@raspberrypi:~/forecast $ python3 forecast.py
INFO:root:Refreshing forecast
INFO:root:Loading OpenWeatherMap provider
Traceback (most recent call last):
  File "forecast.py", line 111, in <module>
    main()
  File "forecast.py", line 68, in main
    openWeather = OpenWeatherMap()
  File "/home/pi/forecast/openweathermap.py", line 10, in __init__
    self.api_key = os.environ["OPEN_WEATHER_MAP_API_KEY"]
  File "/usr/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'OPEN_WEATHER_MAP_API_KEY'
`

**Comment by jefflaplante** [comment]
Hi - Looks like you didn't source the .env file before running the script. If you're running it from your pi directly like you show above, you have to be sure to load the environment variables first and then run the python script.

Ex. `. .env;  /home/pi/forecast/forecast.py`
